// Generates supabase/migrations/20261005000008_template_catalog.sql from src/lib/templates/families.ts
import { writeFileSync } from "node:fs";
import { CATALOG } from "../src/lib/templates/families";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = CATALOG.map((t, i) => {
  const portrait = t.orientation === "portrait";
  const [w, h] = portrait ? [53.98, 85.6] : [85.6, 53.98];
  const photo = portrait ? [t.front[0] === "pPlain" ? [27, 36] : t.front[0] === "pBand" ? [28, 34] : [28, 28]][0] : [t.front[0] === "dark" ? [24, 31] : t.front[0] === "plainLeft" ? [26, 26] : t.front[0] === "diagonal" || t.front[0] === "plainRight" || t.front[0] === "split" || t.front[0] === "hero" || t.front[0] === "banner" || t.front[0] === "sidebar" ? [22, 28.5] : t.front[0] === "heritage" ? [22, 26.2] : [24, 24]][0];
  const front = JSON.stringify({ recipe: { kind: "front", family: t.front[0], cat: t.category, variant: t.front[1] } });
  const back = JSON.stringify({ recipe: { kind: "back", family: portrait ? "portrait" : "landscape", cat: t.category, variant: t.back } });
  return `(null, ${q(t.slug)}, ${q(t.name)}, ${q(t.category)}, ${q(t.orientation)}, ${w}, ${h}, ${photo[0]}, ${photo[1]}, $json$${front}$json$::jsonb, $json$${back}$json$::jsonb, ${100 + i})`;
}).join(",\n");

const sql = `-- EduCard Pro — template catalog (Phase 4b). GENERATED by scripts/gen-catalog-sql.ts; edit src/lib/templates/families.ts instead.
-- Catalog templates are stored as small recipes that the app expands into full designs.
-- The earlier starter 'Community / Association' joins the community category.
update public.card_templates set category = 'community' where organization_id is null and slug = 'community-association';

insert into public.card_templates
  (organization_id, slug, name, category, orientation, width_mm, height_mm, photo_width_mm, photo_height_mm, front_design, back_design, sort_order)
values
${rows}
on conflict (slug) where organization_id is null do update set
  name = excluded.name, category = excluded.category, orientation = excluded.orientation,
  width_mm = excluded.width_mm, height_mm = excluded.height_mm,
  photo_width_mm = excluded.photo_width_mm, photo_height_mm = excluded.photo_height_mm,
  front_design = excluded.front_design, back_design = excluded.back_design,
  sort_order = excluded.sort_order, version = public.card_templates.version + 1;
`;
writeFileSync(new URL("../supabase/migrations/20261005000008_template_catalog.sql", import.meta.url), sql);
console.log("catalog templates:", CATALOG.length);
