-- EduCard Pro — template catalog (Phase 4b). GENERATED by scripts/gen-catalog-sql.ts; edit src/lib/templates/families.ts instead.
-- Campus ID: banner + logo + address line, photo left, name / level / program / ID# right, QR front-right.
-- Uses the organization's own colors, logo and name.

insert into public.card_templates
  (organization_id, slug, name, category, orientation, width_mm, height_mm, photo_width_mm, photo_height_mm, front_design, back_design, sort_order)
values
(null, 'school-campus', 'School Campus ID (banner, logo, QR)', 'school', 'landscape', 85.6, 53.98, 24, 31, $json${"recipe":{"kind":"front","family":"campus","cat":"school","variant":"x"}}$json$::jsonb, $json${"recipe":{"kind":"back","family":"landscape","cat":"school","variant":"campus"}}$json$::jsonb, 200),
(null, 'university-campus', 'University Campus ID (banner, logo, QR)', 'university', 'landscape', 85.6, 53.98, 24, 31, $json${"recipe":{"kind":"front","family":"campus","cat":"university","variant":"x"}}$json$::jsonb, $json${"recipe":{"kind":"back","family":"landscape","cat":"university","variant":"campus"}}$json$::jsonb, 201)
on conflict (slug) where organization_id is null do update set
  name = excluded.name, category = excluded.category, orientation = excluded.orientation,
  width_mm = excluded.width_mm, height_mm = excluded.height_mm,
  photo_width_mm = excluded.photo_width_mm, photo_height_mm = excluded.photo_height_mm,
  front_design = excluded.front_design, back_design = excluded.back_design,
  sort_order = excluded.sort_order, version = public.card_templates.version + 1;
